#version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_new_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NTALE1234
      POSTGRES_DB: user_Information
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: